workflows:
  ttobwa-android-release:
    name: Ttobwa Android Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    environment:
      flutter: 3.27.0
      
    triggering:
      events:
        - push
      branch:
        include:
          - main

    scripts:
      - name: Get dependencies
        script: flutter pub get
        
      - name: Build APK (Release)
        script: flutter build apk --release -v

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
    publishing:
      email:
        recipients:
          - soon.moya@gmail.com
        notify:
          success: true
          failure: true
